processes:
  demo-js:
    command: ./node_modules/.bin/esbuild --bundle --minify --format="esm" ./demo/main.ts --outfile=./demo/dist/main.js --watch=forever
  demo-css:
    command: unbuffer npx @tailwindcss/cli -m -i ./demo/tailwind.css -o ./demo/dist/main.css --watch
  watch-build:
    command: npx tsup --watch
  http-server:
    command: unbuffer python -m http.server -d ./demo 4321
